# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: MappingPolicy
